version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: clinica-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clinica
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - clinica-net

volumes:
  mysql_data:

networks:
  clinica-net:
    driver: bridge
