name: CI - Config Server

on:
  push:
    branches:
      - '**'
    paths:
      - 'config-server/config-server/**' # O pipeline SÓ dispara se houver mudanças nesta pasta
  pull_request:
    branches: [ "main", "develop" ]
    paths:
      - 'config-server/config-server/**'

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./config-server/config-server

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Executar Testes do Config Server
        run: mvn clean test