name: CI - Discovery Server

on:
  push:
    branches:
      - '**'
    paths:
      - 'discovery-server/discovery-server/**' # Só dispara se alterar algo nesta pasta
  pull_request:
    branches: [ "main", "develop" ]
    paths:
      - 'discovery-server/discovery-server/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Executar Testes do Discovery Server
        run: mvn clean test
        working-directory: discovery-server/discovery-server # Aponta para a pasta duplicada