name: CI - Servico de Paciente

on:
  push:
    branches:
      - '**'
    paths:
      - 'servico-paciente/**'
      - '.github/workflows/paciente-ci.yml'
  pull_request:
    branches: [ "main", "develop" ]
    paths:
      - 'servico-paciente/**'
      - '.github/workflows/paciente-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./servico-paciente

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Executar testes do servico de paciente
        run: mvn clean test